-- begin CEAE_NOTIFICATION
alter table CEAE_NOTIFICATION add constraint FK_CEAE_NOTIFICATION_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_CEAE_NOTIFICATION_USER on CEAE_NOTIFICATION (USER_ID)^
-- end CEAE_NOTIFICATION
-- begin CEAE_NOTIFICATION_SUBSCRIPTION
alter table CEAE_NOTIFICATION_SUBSCRIPTION add constraint FK_CEAE_NOTIFICATION_SUBSCRIPTION_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_CEAE_NOTIFICATION_SUBSCRIPTION_USER on CEAE_NOTIFICATION_SUBSCRIPTION (USER_ID)^
-- end CEAE_NOTIFICATION_SUBSCRIPTION
