alter table CEAE_NOTIFICATION_SUBSCRIPTION add constraint FK_CEAE_NOTIFICATION_SUBSCRIPTION_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_CEAE_NOTIFICATION_SUBSCRIPTION_USER on CEAE_NOTIFICATION_SUBSCRIPTION (USER_ID);
